spring.application.name=SettleUp Backend

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/settleup}
spring.datasource.username=${DB_USERNAME:settleup}
spring.datasource.password=${DB_PASSWORD:settleup}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

app.jwt.secret=${JWT_SECRET:}
app.jwt.issuer=settleup
app.jwt.expiration=12h
